# Generated by Django 4.2.8 on 2023-12-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='is_encrypted',
        ),
        migrations.AlterField(
            model_name='file',
            name='download_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
